set(WEBRTC_VERSION "m78")

import_remote(
	"https://chromium.googlesource.com/external/webrtc"
	TAG "branch-heads/${WEBRTC_VERSION}"
	GIT_CONFIG "add remote.origin.fetch +refs/branch-heads/*:refs/remotes/branch-heads/*"
	NO_CMAKE
	ALIAS webrtc_source
)
import_remote("https://github.com/abseil/abseil-cpp.git" TAG "lts_2020_02_25" NO_CMAKE ALIAS abseil_source)
import_remote("https://chromium.googlesource.com/libyuv/libyuv" TAG "master" NO_CMAKE ALIAS libyuv_source)


set(webrtc_SOURCES
	${abseil_source_path}/absl/base/dynamic_annotations.cc
	${abseil_source_path}/absl/base/internal/raw_logging.cc
	${abseil_source_path}/absl/base/internal/throw_delegate.cc
	${abseil_source_path}/absl/strings/ascii.cc
	${abseil_source_path}/absl/strings/internal/memutil.cc
	${abseil_source_path}/absl/strings/match.cc
	${abseil_source_path}/absl/strings/string_view.cc
	${abseil_source_path}/absl/types/bad_optional_access.cc
	${abseil_source_path}/absl/types/bad_variant_access.cc
	${boringssl_source_path}/err_data.c
	${boringssl_source_path}/src/crypto/asn1/a_bitstr.c
	${boringssl_source_path}/src/crypto/asn1/a_bool.c
	${boringssl_source_path}/src/crypto/asn1/a_d2i_fp.c
	${boringssl_source_path}/src/crypto/asn1/a_dup.c
	${boringssl_source_path}/src/crypto/asn1/a_enum.c
	${boringssl_source_path}/src/crypto/asn1/a_gentm.c
	${boringssl_source_path}/src/crypto/asn1/a_i2d_fp.c
	${boringssl_source_path}/src/crypto/asn1/a_int.c
	${boringssl_source_path}/src/crypto/asn1/a_mbstr.c
	${boringssl_source_path}/src/crypto/asn1/a_object.c
	${boringssl_source_path}/src/crypto/asn1/a_octet.c
	${boringssl_source_path}/src/crypto/asn1/a_print.c
	${boringssl_source_path}/src/crypto/asn1/a_strnid.c
	${boringssl_source_path}/src/crypto/asn1/a_time.c
	${boringssl_source_path}/src/crypto/asn1/a_type.c
	${boringssl_source_path}/src/crypto/asn1/a_utctm.c
	${boringssl_source_path}/src/crypto/asn1/a_utf8.c
	${boringssl_source_path}/src/crypto/asn1/asn1_lib.c
	${boringssl_source_path}/src/crypto/asn1/asn1_par.c
	${boringssl_source_path}/src/crypto/asn1/asn_pack.c
	${boringssl_source_path}/src/crypto/asn1/f_enum.c
	${boringssl_source_path}/src/crypto/asn1/f_int.c
	${boringssl_source_path}/src/crypto/asn1/f_string.c
	${boringssl_source_path}/src/crypto/asn1/tasn_dec.c
	${boringssl_source_path}/src/crypto/asn1/tasn_enc.c
	${boringssl_source_path}/src/crypto/asn1/tasn_fre.c
	${boringssl_source_path}/src/crypto/asn1/tasn_new.c
	${boringssl_source_path}/src/crypto/asn1/tasn_typ.c
	${boringssl_source_path}/src/crypto/asn1/tasn_utl.c
	${boringssl_source_path}/src/crypto/asn1/time_support.c
	${boringssl_source_path}/src/crypto/base64/base64.c
	${boringssl_source_path}/src/crypto/bio/bio.c
	${boringssl_source_path}/src/crypto/bio/bio_mem.c
	${boringssl_source_path}/src/crypto/bio/connect.c
	${boringssl_source_path}/src/crypto/bio/fd.c
	${boringssl_source_path}/src/crypto/bio/file.c
	${boringssl_source_path}/src/crypto/bio/hexdump.c
	${boringssl_source_path}/src/crypto/bio/pair.c
	${boringssl_source_path}/src/crypto/bio/printf.c
	${boringssl_source_path}/src/crypto/bio/socket.c
	${boringssl_source_path}/src/crypto/bio/socket_helper.c
	${boringssl_source_path}/src/crypto/bn_extra/bn_asn1.c
	${boringssl_source_path}/src/crypto/bn_extra/convert.c
	${boringssl_source_path}/src/crypto/buf/buf.c
	${boringssl_source_path}/src/crypto/bytestring/asn1_compat.c
	${boringssl_source_path}/src/crypto/bytestring/ber.c
	${boringssl_source_path}/src/crypto/bytestring/cbb.c
	${boringssl_source_path}/src/crypto/bytestring/cbs.c
	${boringssl_source_path}/src/crypto/bytestring/unicode.c
	${boringssl_source_path}/src/crypto/chacha/chacha.c
	${boringssl_source_path}/src/crypto/cipher_extra/cipher_extra.c
	${boringssl_source_path}/src/crypto/cipher_extra/derive_key.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_aesctrhmac.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_aesgcmsiv.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_chacha20poly1305.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_null.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_rc2.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_rc4.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_tls.c
	${boringssl_source_path}/src/crypto/cipher_extra/tls_cbc.c
	${boringssl_source_path}/src/crypto/cmac/cmac.c
	${boringssl_source_path}/src/crypto/conf/conf.c
	${boringssl_source_path}/src/crypto/cpu-aarch64-linux.c
	${boringssl_source_path}/src/crypto/cpu-arm-linux.c
	${boringssl_source_path}/src/crypto/cpu-arm.c
	${boringssl_source_path}/src/crypto/cpu-intel.c
	${boringssl_source_path}/src/crypto/cpu-ppc64le.c
	${boringssl_source_path}/src/crypto/crypto.c
	${boringssl_source_path}/src/crypto/curve25519/spake25519.c
	${boringssl_source_path}/src/crypto/dh/check.c
	${boringssl_source_path}/src/crypto/dh/dh.c
	${boringssl_source_path}/src/crypto/dh/dh_asn1.c
	${boringssl_source_path}/src/crypto/dh/params.c
	${boringssl_source_path}/src/crypto/digest_extra/digest_extra.c
	${boringssl_source_path}/src/crypto/dsa/dsa.c
	${boringssl_source_path}/src/crypto/dsa/dsa_asn1.c
	${boringssl_source_path}/src/crypto/ec_extra/ec_asn1.c
	${boringssl_source_path}/src/crypto/ecdh_extra/ecdh_extra.c
	${boringssl_source_path}/src/crypto/ecdsa_extra/ecdsa_asn1.c
	${boringssl_source_path}/src/crypto/engine/engine.c
	${boringssl_source_path}/src/crypto/err/err.c
	${boringssl_source_path}/src/crypto/evp/digestsign.c
	${boringssl_source_path}/src/crypto/evp/evp.c
	${boringssl_source_path}/src/crypto/evp/evp_asn1.c
	${boringssl_source_path}/src/crypto/evp/evp_ctx.c
	${boringssl_source_path}/src/crypto/evp/p_dsa_asn1.c
	${boringssl_source_path}/src/crypto/evp/p_ec.c
	${boringssl_source_path}/src/crypto/evp/p_ec_asn1.c
	${boringssl_source_path}/src/crypto/evp/p_ed25519.c
	${boringssl_source_path}/src/crypto/evp/p_ed25519_asn1.c
	${boringssl_source_path}/src/crypto/evp/p_rsa.c
	${boringssl_source_path}/src/crypto/evp/p_rsa_asn1.c
	${boringssl_source_path}/src/crypto/evp/p_x25519.c
	${boringssl_source_path}/src/crypto/evp/p_x25519_asn1.c
	${boringssl_source_path}/src/crypto/evp/pbkdf.c
	${boringssl_source_path}/src/crypto/evp/print.c
	${boringssl_source_path}/src/crypto/evp/scrypt.c
	${boringssl_source_path}/src/crypto/evp/sign.c
	${boringssl_source_path}/src/crypto/ex_data.c
	${boringssl_source_path}/src/crypto/fipsmodule/bcm.c
	${boringssl_source_path}/src/crypto/fipsmodule/is_fips.c
	${boringssl_source_path}/src/crypto/fipsmodule/ecdh/ecdh.c
	${boringssl_source_path}/src/crypto/hkdf/hkdf.c
	${boringssl_source_path}/src/crypto/hrss/hrss.c
	${boringssl_source_path}/src/crypto/lhash/lhash.c
	${boringssl_source_path}/src/crypto/mem.c
	${boringssl_source_path}/src/crypto/obj/obj.c
	${boringssl_source_path}/src/crypto/obj/obj_xref.c
	${boringssl_source_path}/src/crypto/pem/pem_all.c
	${boringssl_source_path}/src/crypto/pem/pem_info.c
	${boringssl_source_path}/src/crypto/pem/pem_lib.c
	${boringssl_source_path}/src/crypto/pem/pem_oth.c
	${boringssl_source_path}/src/crypto/pem/pem_pk8.c
	${boringssl_source_path}/src/crypto/pem/pem_pkey.c
	${boringssl_source_path}/src/crypto/pem/pem_x509.c
	${boringssl_source_path}/src/crypto/pem/pem_xaux.c
	${boringssl_source_path}/src/crypto/pkcs7/pkcs7.c
	${boringssl_source_path}/src/crypto/pkcs7/pkcs7_x509.c
	${boringssl_source_path}/src/crypto/pkcs8/p5_pbev2.c
	${boringssl_source_path}/src/crypto/pkcs8/pkcs8.c
	${boringssl_source_path}/src/crypto/pkcs8/pkcs8_x509.c
	${boringssl_source_path}/src/crypto/poly1305/poly1305.c
	${boringssl_source_path}/src/crypto/poly1305/poly1305_arm.c
	${boringssl_source_path}/src/crypto/poly1305/poly1305_vec.c
	${boringssl_source_path}/src/crypto/pool/pool.c
	${boringssl_source_path}/src/crypto/rand_extra/deterministic.c
	${boringssl_source_path}/src/crypto/rand_extra/forkunsafe.c
	${boringssl_source_path}/src/crypto/rand_extra/fuchsia.c
	${boringssl_source_path}/src/crypto/rand_extra/rand_extra.c
	${boringssl_source_path}/src/crypto/rand_extra/windows.c
	${boringssl_source_path}/src/crypto/rc4/rc4.c
	${boringssl_source_path}/src/crypto/refcount_c11.c
	${boringssl_source_path}/src/crypto/refcount_lock.c
	${boringssl_source_path}/src/crypto/rsa_extra/rsa_asn1.c
	${boringssl_source_path}/src/crypto/stack/stack.c
	${boringssl_source_path}/src/crypto/thread.c
	${boringssl_source_path}/src/crypto/thread_none.c
	${boringssl_source_path}/src/crypto/thread_pthread.c
	${boringssl_source_path}/src/crypto/thread_win.c
	${boringssl_source_path}/src/crypto/x509/a_digest.c
	${boringssl_source_path}/src/crypto/x509/a_sign.c
	${boringssl_source_path}/src/crypto/x509/a_strex.c
	${boringssl_source_path}/src/crypto/x509/a_verify.c
	${boringssl_source_path}/src/crypto/x509/algorithm.c
	${boringssl_source_path}/src/crypto/x509/asn1_gen.c
	${boringssl_source_path}/src/crypto/x509/by_dir.c
	${boringssl_source_path}/src/crypto/x509/by_file.c
	${boringssl_source_path}/src/crypto/x509/i2d_pr.c
	${boringssl_source_path}/src/crypto/x509/rsa_pss.c
	${boringssl_source_path}/src/crypto/x509/t_crl.c
	${boringssl_source_path}/src/crypto/x509/t_req.c
	${boringssl_source_path}/src/crypto/x509/t_x509.c
	${boringssl_source_path}/src/crypto/x509/t_x509a.c
	${boringssl_source_path}/src/crypto/x509/x509.c
	${boringssl_source_path}/src/crypto/x509/x509_att.c
	${boringssl_source_path}/src/crypto/x509/x509_cmp.c
	${boringssl_source_path}/src/crypto/x509/x509_d2.c
	${boringssl_source_path}/src/crypto/x509/x509_def.c
	${boringssl_source_path}/src/crypto/x509/x509_ext.c
	${boringssl_source_path}/src/crypto/x509/x509_lu.c
	${boringssl_source_path}/src/crypto/x509/x509_obj.c
	${boringssl_source_path}/src/crypto/x509/x509_r2x.c
	${boringssl_source_path}/src/crypto/x509/x509_req.c
	${boringssl_source_path}/src/crypto/x509/x509_set.c
	${boringssl_source_path}/src/crypto/x509/x509_trs.c
	${boringssl_source_path}/src/crypto/x509/x509_txt.c
	${boringssl_source_path}/src/crypto/x509/x509_v3.c
	${boringssl_source_path}/src/crypto/x509/x509_vfy.c
	${boringssl_source_path}/src/crypto/x509/x509_vpm.c
	${boringssl_source_path}/src/crypto/x509/x509cset.c
	${boringssl_source_path}/src/crypto/x509/x509name.c
	${boringssl_source_path}/src/crypto/x509/x509rset.c
	${boringssl_source_path}/src/crypto/x509/x509spki.c
	${boringssl_source_path}/src/crypto/x509/x_algor.c
	${boringssl_source_path}/src/crypto/x509/x_all.c
	${boringssl_source_path}/src/crypto/x509/x_attrib.c
	${boringssl_source_path}/src/crypto/x509/x_crl.c
	${boringssl_source_path}/src/crypto/x509/x_exten.c
	${boringssl_source_path}/src/crypto/x509/x_info.c
	${boringssl_source_path}/src/crypto/x509/x_name.c
	${boringssl_source_path}/src/crypto/x509/x_pkey.c
	${boringssl_source_path}/src/crypto/x509/x_pubkey.c
	${boringssl_source_path}/src/crypto/x509/x_req.c
	${boringssl_source_path}/src/crypto/x509/x_sig.c
	${boringssl_source_path}/src/crypto/x509/x_spki.c
	${boringssl_source_path}/src/crypto/x509/x_val.c
	${boringssl_source_path}/src/crypto/x509/x_x509.c
	${boringssl_source_path}/src/crypto/x509/x_x509a.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_cache.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_data.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_lib.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_map.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_node.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_tree.c
	${boringssl_source_path}/src/crypto/x509v3/v3_akey.c
	${boringssl_source_path}/src/crypto/x509v3/v3_akeya.c
	${boringssl_source_path}/src/crypto/x509v3/v3_alt.c
	${boringssl_source_path}/src/crypto/x509v3/v3_bcons.c
	${boringssl_source_path}/src/crypto/x509v3/v3_bitst.c
	${boringssl_source_path}/src/crypto/x509v3/v3_conf.c
	${boringssl_source_path}/src/crypto/x509v3/v3_cpols.c
	${boringssl_source_path}/src/crypto/x509v3/v3_crld.c
	${boringssl_source_path}/src/crypto/x509v3/v3_enum.c
	${boringssl_source_path}/src/crypto/x509v3/v3_extku.c
	${boringssl_source_path}/src/crypto/x509v3/v3_genn.c
	${boringssl_source_path}/src/crypto/x509v3/v3_ia5.c
	${boringssl_source_path}/src/crypto/x509v3/v3_info.c
	${boringssl_source_path}/src/crypto/x509v3/v3_int.c
	${boringssl_source_path}/src/crypto/x509v3/v3_lib.c
	${boringssl_source_path}/src/crypto/x509v3/v3_ncons.c
	${boringssl_source_path}/src/crypto/x509v3/v3_ocsp.c
	${boringssl_source_path}/src/crypto/x509v3/v3_pci.c
	${boringssl_source_path}/src/crypto/x509v3/v3_pcia.c
	${boringssl_source_path}/src/crypto/x509v3/v3_pcons.c
	${boringssl_source_path}/src/crypto/x509v3/v3_pku.c
	${boringssl_source_path}/src/crypto/x509v3/v3_pmaps.c
	${boringssl_source_path}/src/crypto/x509v3/v3_prn.c
	${boringssl_source_path}/src/crypto/x509v3/v3_purp.c
	${boringssl_source_path}/src/crypto/x509v3/v3_skey.c
	${boringssl_source_path}/src/crypto/x509v3/v3_sxnet.c
	${boringssl_source_path}/src/crypto/x509v3/v3_utl.c
	${boringssl_source_path}/src/ssl/bio_ssl.cc
	${boringssl_source_path}/src/ssl/d1_both.cc
	${boringssl_source_path}/src/ssl/d1_lib.cc
	${boringssl_source_path}/src/ssl/d1_pkt.cc
	${boringssl_source_path}/src/ssl/d1_srtp.cc
	${boringssl_source_path}/src/ssl/dtls_method.cc
	${boringssl_source_path}/src/ssl/dtls_record.cc
	${boringssl_source_path}/src/ssl/handshake.cc
	${boringssl_source_path}/src/ssl/handshake_client.cc
	${boringssl_source_path}/src/ssl/handshake_server.cc
	${boringssl_source_path}/src/ssl/s3_both.cc
	${boringssl_source_path}/src/ssl/s3_lib.cc
	${boringssl_source_path}/src/ssl/s3_pkt.cc
	${boringssl_source_path}/src/ssl/ssl_aead_ctx.cc
	${boringssl_source_path}/src/ssl/ssl_asn1.cc
	${boringssl_source_path}/src/ssl/ssl_buffer.cc
	${boringssl_source_path}/src/ssl/ssl_cert.cc
	${boringssl_source_path}/src/ssl/ssl_cipher.cc
	${boringssl_source_path}/src/ssl/ssl_file.cc
	${boringssl_source_path}/src/ssl/ssl_key_share.cc
	${boringssl_source_path}/src/ssl/ssl_lib.cc
	${boringssl_source_path}/src/ssl/ssl_privkey.cc
	${boringssl_source_path}/src/ssl/ssl_session.cc
	${boringssl_source_path}/src/ssl/ssl_stat.cc
	${boringssl_source_path}/src/ssl/ssl_transcript.cc
	${boringssl_source_path}/src/ssl/ssl_versions.cc
	${boringssl_source_path}/src/ssl/ssl_x509.cc
	${boringssl_source_path}/src/ssl/t1_enc.cc
	${boringssl_source_path}/src/ssl/t1_lib.cc
	${boringssl_source_path}/src/ssl/tls13_both.cc
	${boringssl_source_path}/src/ssl/tls13_client.cc
	${boringssl_source_path}/src/ssl/tls13_enc.cc
	${boringssl_source_path}/src/ssl/tls13_server.cc
	${boringssl_source_path}/src/ssl/tls_method.cc
	${boringssl_source_path}/src/ssl/tls_record.cc
	${boringssl_source_path}/src/third_party/fiat/curve25519.c
	${jsoncpp_source_path}/src/lib_json/json_reader.cpp
	${jsoncpp_source_path}/src/lib_json/json_value.cpp
	${jsoncpp_source_path}/src/lib_json/json_writer.cpp
	${libyuv_source_path}/source/compare.cc
	${libyuv_source_path}/source/compare_common.cc
	${libyuv_source_path}/source/compare_gcc.cc
	${libyuv_source_path}/source/convert.cc
	${libyuv_source_path}/source/convert_argb.cc
	${libyuv_source_path}/source/convert_from.cc
	${libyuv_source_path}/source/convert_from_argb.cc
	${libyuv_source_path}/source/convert_jpeg.cc
	${libyuv_source_path}/source/convert_to_argb.cc
	${libyuv_source_path}/source/convert_to_i420.cc
	${libyuv_source_path}/source/cpu_id.cc
	${libyuv_source_path}/source/mjpeg_decoder.cc
	${libyuv_source_path}/source/mjpeg_validate.cc
	${libyuv_source_path}/source/planar_functions.cc
	${libyuv_source_path}/source/compare_neon.cc
	${libyuv_source_path}/source/compare_neon64.cc
	${libyuv_source_path}/source/rotate.cc
	${libyuv_source_path}/source/rotate_any.cc
	${libyuv_source_path}/source/rotate_argb.cc
	${libyuv_source_path}/source/rotate_common.cc
	${libyuv_source_path}/source/rotate_gcc.cc
	${libyuv_source_path}/source/rotate_neon.cc
	${libyuv_source_path}/source/rotate_neon64.cc
	${libyuv_source_path}/source/row_any.cc
	${libyuv_source_path}/source/row_common.cc
	${libyuv_source_path}/source/row_gcc.cc
	${libyuv_source_path}/source/row_neon.cc
	${libyuv_source_path}/source/row_neon64.cc
	${libyuv_source_path}/source/scale.cc
	${libyuv_source_path}/source/scale_any.cc
	${libyuv_source_path}/source/scale_argb.cc
	${libyuv_source_path}/source/scale_common.cc
	${libyuv_source_path}/source/scale_gcc.cc
	${libyuv_source_path}/source/scale_neon.cc
	${libyuv_source_path}/source/scale_neon64.cc
	${libyuv_source_path}/source/video_common.cc
	${CMAKE_CURRENT_SOURCE_DIR}/third_party/pffft/src/pffft.c
	${rnnoise_source_path}/rnn_vad_weights.cc
	${webrtc_source_path}/api/audio/audio_frame.cc
	${webrtc_source_path}/api/audio/channel_layout.cc
	${webrtc_source_path}/api/audio/echo_canceller3_config.cc
	${webrtc_source_path}/api/audio/echo_canceller3_factory.cc
	${webrtc_source_path}/api/audio_codecs/L16/audio_decoder_L16.cc
	${webrtc_source_path}/api/audio_codecs/L16/audio_encoder_L16.cc
	${webrtc_source_path}/api/audio_codecs/audio_codec_pair_id.cc
	${webrtc_source_path}/api/audio_codecs/audio_decoder.cc
	${webrtc_source_path}/api/audio_codecs/audio_encoder.cc
	${webrtc_source_path}/api/audio_codecs/audio_format.cc
	${webrtc_source_path}/api/audio_codecs/builtin_audio_decoder_factory.cc
	${webrtc_source_path}/api/audio_codecs/builtin_audio_encoder_factory.cc
	${webrtc_source_path}/api/audio_codecs/g711/audio_decoder_g711.cc
	${webrtc_source_path}/api/audio_codecs/g711/audio_encoder_g711.cc
	${webrtc_source_path}/api/audio_codecs/g722/audio_decoder_g722.cc
	${webrtc_source_path}/api/audio_codecs/g722/audio_encoder_g722.cc
	${webrtc_source_path}/api/audio_codecs/ilbc/audio_decoder_ilbc.cc
	${webrtc_source_path}/api/audio_codecs/ilbc/audio_encoder_ilbc.cc
	${webrtc_source_path}/api/audio_codecs/isac/audio_decoder_isac_fix.cc
	${webrtc_source_path}/api/audio_codecs/isac/audio_decoder_isac_float.cc
	${webrtc_source_path}/api/audio_codecs/isac/audio_encoder_isac_fix.cc
	${webrtc_source_path}/api/audio_codecs/isac/audio_encoder_isac_float.cc
	${webrtc_source_path}/api/audio_codecs/opus/audio_decoder_multi_channel_opus.cc
	${webrtc_source_path}/api/audio_codecs/opus/audio_decoder_opus.cc
	${webrtc_source_path}/api/audio_codecs/opus/audio_encoder_multi_channel_opus.cc
	${webrtc_source_path}/api/audio_codecs/opus/audio_encoder_multi_channel_opus_config.cc
	${webrtc_source_path}/api/audio_codecs/opus/audio_encoder_opus.cc
	${webrtc_source_path}/api/audio_codecs/opus/audio_encoder_opus_config.cc
	${webrtc_source_path}/api/audio_options.cc
	${webrtc_source_path}/api/call/transport.cc
	${webrtc_source_path}/api/candidate.cc
	${webrtc_source_path}/api/create_peerconnection_factory.cc
	${webrtc_source_path}/api/crypto/crypto_options.cc
	${webrtc_source_path}/api/data_channel_interface.cc
	${webrtc_source_path}/api/dtls_transport_interface.cc
	${webrtc_source_path}/api/ice_transport_factory.cc
	${webrtc_source_path}/api/jsep.cc
	${webrtc_source_path}/api/jsep_ice_candidate.cc
	${webrtc_source_path}/api/media_stream_interface.cc
	${webrtc_source_path}/api/media_types.cc
	${webrtc_source_path}/api/peer_connection_interface.cc
	${webrtc_source_path}/api/proxy.cc
	${webrtc_source_path}/api/rtc_error.cc
	${webrtc_source_path}/api/rtc_event_log_output_file.cc
	${webrtc_source_path}/api/rtc_event_log/rtc_event.cc
	${webrtc_source_path}/api/rtc_event_log/rtc_event_log.cc
	${webrtc_source_path}/api/rtc_event_log/rtc_event_log_factory.cc
	${webrtc_source_path}/api/rtp_headers.cc
	${webrtc_source_path}/api/rtp_packet_info.cc
	${webrtc_source_path}/api/rtp_parameters.cc
	${webrtc_source_path}/api/rtp_receiver_interface.cc
	${webrtc_source_path}/api/rtp_sender_interface.cc
	${webrtc_source_path}/api/rtp_transceiver_interface.cc
	${webrtc_source_path}/api/sctp_transport_interface.cc
	${webrtc_source_path}/api/stats_types.cc
	${webrtc_source_path}/api/task_queue/default_task_queue_factory_stdlib.cc
	${webrtc_source_path}/api/task_queue/task_queue_base.cc
	${webrtc_source_path}/api/transport/bitrate_settings.cc
	${webrtc_source_path}/api/transport/field_trial_based_config.cc
	${webrtc_source_path}/api/transport/goog_cc_factory.cc
	${webrtc_source_path}/api/transport/media/audio_transport.cc
	${webrtc_source_path}/api/transport/media/video_transport.cc
	${webrtc_source_path}/api/transport/network_types.cc
	${webrtc_source_path}/api/units/data_rate.cc
	${webrtc_source_path}/api/units/data_size.cc
	${webrtc_source_path}/api/units/time_delta.cc
	${webrtc_source_path}/api/units/timestamp.cc
	${webrtc_source_path}/api/video/builtin_video_bitrate_allocator_factory.cc
	${webrtc_source_path}/api/video/color_space.cc
	${webrtc_source_path}/api/video/encoded_frame.cc
	${webrtc_source_path}/api/video/encoded_image.cc
	${webrtc_source_path}/api/video/hdr_metadata.cc
	${webrtc_source_path}/api/video/i010_buffer.cc
	${webrtc_source_path}/api/video/i420_buffer.cc
	${webrtc_source_path}/api/video/video_bitrate_allocation.cc
	${webrtc_source_path}/api/video/video_bitrate_allocator.cc
	${webrtc_source_path}/api/video/video_content_type.cc
	${webrtc_source_path}/api/video/video_frame.cc
	${webrtc_source_path}/api/video/video_frame_buffer.cc
	${webrtc_source_path}/api/video/video_source_interface.cc
	${webrtc_source_path}/api/video/video_stream_decoder_create.cc
	${webrtc_source_path}/api/video/video_stream_encoder_create.cc
	${webrtc_source_path}/api/video/video_timing.cc
	${webrtc_source_path}/api/video_codecs/builtin_video_decoder_factory.cc
	${webrtc_source_path}/api/video_codecs/builtin_video_encoder_factory.cc
	${webrtc_source_path}/api/video_codecs/sdp_video_format.cc
	${webrtc_source_path}/api/video_codecs/video_codec.cc
	${webrtc_source_path}/api/video_codecs/video_decoder.cc
	${webrtc_source_path}/api/video_codecs/video_decoder_factory.cc
	${webrtc_source_path}/api/video_codecs/video_decoder_software_fallback_wrapper.cc
	${webrtc_source_path}/api/video_codecs/video_encoder.cc
	${webrtc_source_path}/api/video_codecs/video_encoder_config.cc
	${webrtc_source_path}/api/video_codecs/video_encoder_software_fallback_wrapper.cc
	${webrtc_source_path}/api/video_codecs/vp8_frame_config.cc
	${webrtc_source_path}/api/video_codecs/vp8_temporal_layers.cc
	${webrtc_source_path}/api/video_codecs/vp8_temporal_layers_factory.cc
	${webrtc_source_path}/audio/audio_level.cc
	${webrtc_source_path}/audio/audio_receive_stream.cc
	${webrtc_source_path}/audio/audio_send_stream.cc
	${webrtc_source_path}/audio/audio_state.cc
	${webrtc_source_path}/audio/audio_transport_impl.cc
	${webrtc_source_path}/audio/channel_receive.cc
	${webrtc_source_path}/audio/channel_send.cc
	${webrtc_source_path}/audio/null_audio_poller.cc
	${webrtc_source_path}/audio/remix_resample.cc
	${webrtc_source_path}/audio/utility/audio_frame_operations.cc
	${webrtc_source_path}/audio/utility/channel_mixer.cc
	${webrtc_source_path}/audio/utility/channel_mixing_matrix.cc
	${webrtc_source_path}/call/audio_receive_stream.cc
	${webrtc_source_path}/call/audio_send_stream.cc
	${webrtc_source_path}/call/audio_state.cc
	${webrtc_source_path}/call/bitrate_allocator.cc
	${webrtc_source_path}/call/call.cc
	${webrtc_source_path}/call/call_config.cc
	${webrtc_source_path}/call/call_factory.cc
	${webrtc_source_path}/call/degraded_call.cc
	${webrtc_source_path}/call/fake_network_pipe.cc
	${webrtc_source_path}/call/flexfec_receive_stream.cc
	${webrtc_source_path}/call/flexfec_receive_stream_impl.cc
	${webrtc_source_path}/call/receive_time_calculator.cc
	${webrtc_source_path}/call/rtcp_demuxer.cc
	${webrtc_source_path}/call/rtp_bitrate_configurator.cc
	${webrtc_source_path}/call/rtp_config.cc
	${webrtc_source_path}/call/rtp_demuxer.cc
	${webrtc_source_path}/call/rtp_payload_params.cc
	${webrtc_source_path}/call/rtp_rtcp_demuxer_helper.cc
	${webrtc_source_path}/call/rtp_stream_receiver_controller.cc
	${webrtc_source_path}/call/rtp_transport_controller_send.cc
	${webrtc_source_path}/call/rtp_video_sender.cc
	${webrtc_source_path}/call/rtx_receive_stream.cc
	${webrtc_source_path}/call/simulated_network.cc
	${webrtc_source_path}/call/syncable.cc
	${webrtc_source_path}/call/video_receive_stream.cc
	${webrtc_source_path}/call/video_send_stream.cc
	${webrtc_source_path}/common_audio/audio_converter.cc
	${webrtc_source_path}/common_audio/audio_util.cc
	${webrtc_source_path}/common_audio/channel_buffer.cc
	${webrtc_source_path}/common_audio/fir_filter_c.cc
	${webrtc_source_path}/common_audio/fir_filter_factory.cc
	${webrtc_source_path}/common_audio/real_fourier.cc
	${webrtc_source_path}/common_audio/real_fourier_ooura.cc
	${webrtc_source_path}/common_audio/resampler/push_resampler.cc
	${webrtc_source_path}/common_audio/resampler/push_sinc_resampler.cc
	${webrtc_source_path}/common_audio/resampler/resampler.cc
	${webrtc_source_path}/common_audio/resampler/sinc_resampler.cc
	${webrtc_source_path}/common_audio/ring_buffer.c
	${webrtc_source_path}/common_audio/signal_processing/auto_corr_to_refl_coef.c
	${webrtc_source_path}/common_audio/signal_processing/auto_correlation.c
	${webrtc_source_path}/common_audio/signal_processing/complex_bit_reverse.c
	${webrtc_source_path}/common_audio/signal_processing/complex_fft.c
	${webrtc_source_path}/common_audio/signal_processing/copy_set_operations.c
	${webrtc_source_path}/common_audio/signal_processing/cross_correlation.c
	${webrtc_source_path}/common_audio/signal_processing/division_operations.c
	${webrtc_source_path}/common_audio/signal_processing/dot_product_with_scale.cc
	${webrtc_source_path}/common_audio/signal_processing/downsample_fast.c
	${webrtc_source_path}/common_audio/signal_processing/energy.c
	${webrtc_source_path}/common_audio/signal_processing/filter_ar.c
	${webrtc_source_path}/common_audio/signal_processing/filter_ar_fast_q12.c
	${webrtc_source_path}/common_audio/signal_processing/filter_ma_fast_q12.c
	${webrtc_source_path}/common_audio/signal_processing/get_hanning_window.c
	${webrtc_source_path}/common_audio/signal_processing/get_scaling_square.c
	${webrtc_source_path}/common_audio/signal_processing/ilbc_specific_functions.c
	${webrtc_source_path}/common_audio/signal_processing/levinson_durbin.c
	${webrtc_source_path}/common_audio/signal_processing/lpc_to_refl_coef.c
	${webrtc_source_path}/common_audio/signal_processing/min_max_operations.c
	${webrtc_source_path}/common_audio/signal_processing/randomization_functions.c
	${webrtc_source_path}/common_audio/signal_processing/real_fft.c
	${webrtc_source_path}/common_audio/signal_processing/refl_coef_to_lpc.c
	${webrtc_source_path}/common_audio/signal_processing/resample.c
	${webrtc_source_path}/common_audio/signal_processing/resample_48khz.c
	${webrtc_source_path}/common_audio/signal_processing/resample_by_2.c
	${webrtc_source_path}/common_audio/signal_processing/resample_by_2_internal.c
	${webrtc_source_path}/common_audio/signal_processing/resample_fractional.c
	${webrtc_source_path}/common_audio/signal_processing/spl_init.c
	${webrtc_source_path}/common_audio/signal_processing/spl_inl.c
	${webrtc_source_path}/common_audio/signal_processing/spl_sqrt.c
	${webrtc_source_path}/common_audio/signal_processing/splitting_filter.c
	${webrtc_source_path}/common_audio/signal_processing/sqrt_of_one_minus_x_squared.c
	${webrtc_source_path}/common_audio/signal_processing/vector_scaling_operations.c
	${webrtc_source_path}/common_audio/smoothing_filter.cc
	${webrtc_source_path}/common_audio/third_party/fft4g/fft4g.c
	${webrtc_source_path}/common_audio/third_party/spl_sqrt_floor/spl_sqrt_floor.c
	${webrtc_source_path}/common_audio/vad/vad.cc
	${webrtc_source_path}/common_audio/vad/vad_core.c
	${webrtc_source_path}/common_audio/vad/vad_filterbank.c
	${webrtc_source_path}/common_audio/vad/vad_gmm.c
	${webrtc_source_path}/common_audio/vad/vad_sp.c
	${webrtc_source_path}/common_audio/vad/webrtc_vad.c
	${webrtc_source_path}/common_audio/wav_file.cc
	${webrtc_source_path}/common_audio/wav_header.cc
	${webrtc_source_path}/common_audio/window_generator.cc
	${webrtc_source_path}/common_video/bitrate_adjuster.cc
	${webrtc_source_path}/common_video/frame_rate_estimator.cc
	${webrtc_source_path}/common_video/generic_frame_descriptor/generic_frame_info.cc
	${webrtc_source_path}/common_video/h264/h264_bitstream_parser.cc
	${webrtc_source_path}/common_video/h264/h264_common.cc
	${webrtc_source_path}/common_video/h264/pps_parser.cc
	${webrtc_source_path}/common_video/h264/sps_parser.cc
	${webrtc_source_path}/common_video/h264/sps_vui_rewriter.cc
	${webrtc_source_path}/common_video/i420_buffer_pool.cc
	${webrtc_source_path}/common_video/incoming_video_stream.cc
	${webrtc_source_path}/common_video/libyuv/webrtc_libyuv.cc
	${webrtc_source_path}/common_video/video_frame_buffer.cc
	${webrtc_source_path}/common_video/video_render_frames.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_alr_state.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_audio_network_adaptation.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_audio_playout.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_audio_receive_stream_config.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_audio_send_stream_config.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_bwe_update_delay_based.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_bwe_update_loss_based.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_dtls_transport_state.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_dtls_writable_state.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_generic_ack_received.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_generic_packet_received.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_generic_packet_sent.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_ice_candidate_pair.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_ice_candidate_pair_config.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_probe_cluster_created.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_probe_result_failure.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_probe_result_success.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_route_change.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_rtcp_packet_incoming.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_rtcp_packet_outgoing.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_rtp_packet_incoming.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_rtp_packet_outgoing.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_video_receive_stream_config.cc
	${webrtc_source_path}/logging/rtc_event_log/events/rtc_event_video_send_stream_config.cc
	${webrtc_source_path}/logging/rtc_event_log/ice_logger.cc
	${webrtc_source_path}/logging/rtc_event_log/logged_events.cc
	${webrtc_source_path}/logging/rtc_event_log/rtc_event_log_impl.cc
	${webrtc_source_path}/logging/rtc_event_log/rtc_event_processor.cc
	${webrtc_source_path}/logging/rtc_event_log/rtc_stream_config.cc
	${webrtc_source_path}/media/base/adapted_video_track_source.cc
	${webrtc_source_path}/media/base/codec.cc
	${webrtc_source_path}/media/base/h264_profile_level_id.cc
	${webrtc_source_path}/media/base/media_channel.cc
	${webrtc_source_path}/media/base/media_constants.cc
	${webrtc_source_path}/media/base/media_engine.cc
	${webrtc_source_path}/media/base/rid_description.cc
	${webrtc_source_path}/media/base/rtp_data_engine.cc
	${webrtc_source_path}/media/base/rtp_utils.cc
	${webrtc_source_path}/media/base/stream_params.cc
	${webrtc_source_path}/media/base/turn_utils.cc
	${webrtc_source_path}/media/base/video_adapter.cc
	${webrtc_source_path}/media/base/video_broadcaster.cc
	${webrtc_source_path}/media/base/video_common.cc
	${webrtc_source_path}/media/base/video_source_base.cc
	${webrtc_source_path}/media/base/vp9_profile.cc
	${webrtc_source_path}/media/engine/adm_helpers.cc
	${webrtc_source_path}/media/engine/constants.cc
	${webrtc_source_path}/media/engine/encoder_simulcast_proxy.cc
	${webrtc_source_path}/media/engine/internal_decoder_factory.cc
	${webrtc_source_path}/media/engine/internal_encoder_factory.cc
	${webrtc_source_path}/media/engine/multiplex_codec_factory.cc
	${webrtc_source_path}/media/engine/payload_type_mapper.cc
	${webrtc_source_path}/media/engine/simulcast.cc
	${webrtc_source_path}/media/engine/simulcast_encoder_adapter.cc
	${webrtc_source_path}/media/engine/unhandled_packets_buffer.cc
	${webrtc_source_path}/media/engine/webrtc_media_engine.cc
	${webrtc_source_path}/media/engine/webrtc_media_engine_defaults.cc
	${webrtc_source_path}/media/engine/webrtc_video_engine.cc
	${webrtc_source_path}/media/engine/webrtc_voice_engine.cc
	${webrtc_source_path}/media/sctp/sctp_transport.cc
	${webrtc_source_path}/modules/audio_coding/acm2/acm_receiver.cc
	${webrtc_source_path}/modules/audio_coding/acm2/acm_resampler.cc
	${webrtc_source_path}/modules/audio_coding/acm2/audio_coding_module.cc
	${webrtc_source_path}/modules/audio_coding/acm2/call_statistics.cc
	${webrtc_source_path}/modules/audio_coding/audio_network_adaptor/audio_network_adaptor_config.cc
	${webrtc_source_path}/modules/audio_coding/audio_network_adaptor/audio_network_adaptor_impl.cc
	${webrtc_source_path}/modules/audio_coding/audio_network_adaptor/bitrate_controller.cc
	${webrtc_source_path}/modules/audio_coding/audio_network_adaptor/channel_controller.cc
	${webrtc_source_path}/modules/audio_coding/audio_network_adaptor/controller.cc
	${webrtc_source_path}/modules/audio_coding/audio_network_adaptor/controller_manager.cc
	${webrtc_source_path}/modules/audio_coding/audio_network_adaptor/debug_dump_writer.cc
	${webrtc_source_path}/modules/audio_coding/audio_network_adaptor/dtx_controller.cc
	${webrtc_source_path}/modules/audio_coding/audio_network_adaptor/event_log_writer.cc
	${webrtc_source_path}/modules/audio_coding/audio_network_adaptor/frame_length_controller.cc
	${webrtc_source_path}/modules/audio_coding/codecs/cng/audio_encoder_cng.cc
	${webrtc_source_path}/modules/audio_coding/codecs/cng/webrtc_cng.cc
	${webrtc_source_path}/modules/audio_coding/codecs/g711/audio_decoder_pcm.cc
	${webrtc_source_path}/modules/audio_coding/codecs/g711/audio_encoder_pcm.cc
	${webrtc_source_path}/modules/audio_coding/codecs/g711/g711_interface.c
	${webrtc_source_path}/modules/audio_coding/codecs/g722/audio_decoder_g722.cc
	${webrtc_source_path}/modules/audio_coding/codecs/g722/audio_encoder_g722.cc
	${webrtc_source_path}/modules/audio_coding/codecs/g722/g722_interface.c
	${webrtc_source_path}/modules/audio_coding/codecs/ilbc/audio_decoder_ilbc.cc
	${webrtc_source_path}/modules/audio_coding/codecs/ilbc/audio_encoder_ilbc.cc
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/arith_routines.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/arith_routines_hist.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/arith_routines_logist.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/audio_decoder_isacfix.cc
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/audio_encoder_isacfix.cc
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/bandwidth_estimator.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/decode.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/decode_bwe.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/decode_plc.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/encode.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/entropy_coding.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/fft.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/filterbank_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/filterbanks.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/filters.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/initialize.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/isacfix.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/lattice.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/lattice_c.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/lpc_masking_model.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/lpc_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/pitch_estimator.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/pitch_estimator_c.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/pitch_filter.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/pitch_filter_c.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/pitch_gain_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/pitch_lag_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/spectrum_ar_model_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/transform.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/fix/source/transform_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/audio_decoder_isac.cc
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/audio_encoder_isac.cc
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/bandwidth_estimator.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/crc.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/decode.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/decode_bwe.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/encode.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/encode_lpc_swb.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/entropy_coding.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/filter_functions.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/filterbanks.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/intialize.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/isac.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/isac_vad.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/lattice.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/lpc_analysis.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/lpc_gain_swb_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/lpc_shape_swb12_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/lpc_shape_swb16_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/lpc_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/pitch_estimator.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/pitch_filter.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/pitch_gain_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/pitch_lag_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/spectrum_ar_model_tables.c
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/source/transform.c
	${webrtc_source_path}/modules/audio_coding/codecs/legacy_encoded_audio_frame.cc
	${webrtc_source_path}/modules/audio_coding/codecs/opus/audio_coder_opus_common.cc
	${webrtc_source_path}/modules/audio_coding/codecs/opus/audio_decoder_multi_channel_opus_impl.cc
	${webrtc_source_path}/modules/audio_coding/codecs/opus/audio_decoder_opus.cc
	${webrtc_source_path}/modules/audio_coding/codecs/opus/audio_encoder_multi_channel_opus_impl.cc
	${webrtc_source_path}/modules/audio_coding/codecs/opus/audio_encoder_opus.cc
	${webrtc_source_path}/modules/audio_coding/codecs/pcm16b/audio_decoder_pcm16b.cc
	${webrtc_source_path}/modules/audio_coding/codecs/pcm16b/audio_encoder_pcm16b.cc
	${webrtc_source_path}/modules/audio_coding/codecs/pcm16b/pcm16b.c
	${webrtc_source_path}/modules/audio_coding/codecs/pcm16b/pcm16b_common.cc
	${webrtc_source_path}/modules/audio_coding/codecs/red/audio_encoder_copy_red.cc
	${webrtc_source_path}/modules/audio_coding/neteq/accelerate.cc
	${webrtc_source_path}/modules/audio_coding/neteq/audio_multi_vector.cc
	${webrtc_source_path}/modules/audio_coding/neteq/audio_vector.cc
	${webrtc_source_path}/modules/audio_coding/neteq/background_noise.cc
	${webrtc_source_path}/modules/audio_coding/neteq/buffer_level_filter.cc
	${webrtc_source_path}/modules/audio_coding/neteq/comfort_noise.cc
	${webrtc_source_path}/modules/audio_coding/neteq/cross_correlation.cc
	${webrtc_source_path}/modules/audio_coding/neteq/decision_logic.cc
	${webrtc_source_path}/modules/audio_coding/neteq/decoder_database.cc
	${webrtc_source_path}/modules/audio_coding/neteq/delay_manager.cc
	${webrtc_source_path}/modules/audio_coding/neteq/dsp_helper.cc
	${webrtc_source_path}/modules/audio_coding/neteq/dtmf_buffer.cc
	${webrtc_source_path}/modules/audio_coding/neteq/dtmf_tone_generator.cc
	${webrtc_source_path}/modules/audio_coding/neteq/expand.cc
	${webrtc_source_path}/modules/audio_coding/neteq/expand_uma_logger.cc
	${webrtc_source_path}/modules/audio_coding/neteq/histogram.cc
	${webrtc_source_path}/modules/audio_coding/neteq/merge.cc
	${webrtc_source_path}/modules/audio_coding/neteq/nack_tracker.cc
	${webrtc_source_path}/modules/audio_coding/neteq/neteq_impl.cc
	${webrtc_source_path}/modules/audio_coding/neteq/normal.cc
	${webrtc_source_path}/modules/audio_coding/neteq/packet.cc
	${webrtc_source_path}/modules/audio_coding/neteq/packet_buffer.cc
	${webrtc_source_path}/modules/audio_coding/neteq/post_decode_vad.cc
	${webrtc_source_path}/modules/audio_coding/neteq/preemptive_expand.cc
	${webrtc_source_path}/modules/audio_coding/neteq/random_vector.cc
	${webrtc_source_path}/modules/audio_coding/neteq/red_payload_splitter.cc
	${webrtc_source_path}/modules/audio_coding/neteq/statistics_calculator.cc
	${webrtc_source_path}/modules/audio_coding/neteq/sync_buffer.cc
	${webrtc_source_path}/modules/audio_coding/neteq/time_stretch.cc
	${webrtc_source_path}/modules/audio_coding/neteq/timestamp_scaler.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/audio_loop.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/audio_sink.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/constant_pcm_packet_source.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/encode_neteq_input.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/fake_decode_from_file.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/input_audio_file.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/neteq_replacement_input.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/packet.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/packet_source.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/resample_input_audio_file.cc
	${webrtc_source_path}/modules/audio_coding/neteq/tools/rtp_generator.cc
	${webrtc_source_path}/modules/audio_device/audio_device_buffer.cc
	${webrtc_source_path}/modules/audio_device/audio_device_generic.cc
	${webrtc_source_path}/modules/audio_device/audio_device_impl.cc
	${webrtc_source_path}/modules/audio_device/dummy/audio_device_dummy.cc
	${webrtc_source_path}/modules/audio_device/dummy/file_audio_device.cc
	${webrtc_source_path}/modules/audio_device/dummy/file_audio_device_factory.cc
	${webrtc_source_path}/modules/audio_device/fine_audio_buffer.cc
	${webrtc_source_path}/modules/audio_mixer/audio_frame_manipulator.cc
	${webrtc_source_path}/modules/audio_mixer/audio_mixer_impl.cc
	${webrtc_source_path}/modules/audio_mixer/default_output_rate_calculator.cc
	${webrtc_source_path}/modules/audio_mixer/frame_combiner.cc
	${webrtc_source_path}/modules/audio_processing/aec3/adaptive_fir_filter.cc
	${webrtc_source_path}/modules/audio_processing/aec3/aec3_common.cc
	${webrtc_source_path}/modules/audio_processing/aec3/aec3_fft.cc
	${webrtc_source_path}/modules/audio_processing/aec3/aec_state.cc
	${webrtc_source_path}/modules/audio_processing/aec3/api_call_jitter_metrics.cc
	${webrtc_source_path}/modules/audio_processing/aec3/block_buffer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/block_delay_buffer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/block_framer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/block_processor.cc
	${webrtc_source_path}/modules/audio_processing/aec3/block_processor_metrics.cc
	${webrtc_source_path}/modules/audio_processing/aec3/clockdrift_detector.cc
	${webrtc_source_path}/modules/audio_processing/aec3/comfort_noise_generator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/decimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/downsampled_render_buffer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/echo_audibility.cc
	${webrtc_source_path}/modules/audio_processing/aec3/echo_canceller3.cc
	${webrtc_source_path}/modules/audio_processing/aec3/echo_path_delay_estimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/echo_path_variability.cc
	${webrtc_source_path}/modules/audio_processing/aec3/echo_remover.cc
	${webrtc_source_path}/modules/audio_processing/aec3/echo_remover_metrics.cc
	${webrtc_source_path}/modules/audio_processing/aec3/erl_estimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/erle_estimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/fft_buffer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/filter_analyzer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/frame_blocker.cc
	${webrtc_source_path}/modules/audio_processing/aec3/fullband_erle_estimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/main_filter_update_gain.cc
	${webrtc_source_path}/modules/audio_processing/aec3/matched_filter.cc
	${webrtc_source_path}/modules/audio_processing/aec3/matched_filter_lag_aggregator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/moving_average.cc
	${webrtc_source_path}/modules/audio_processing/aec3/render_buffer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/render_delay_buffer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/render_delay_controller.cc
	${webrtc_source_path}/modules/audio_processing/aec3/render_delay_controller_metrics.cc
	${webrtc_source_path}/modules/audio_processing/aec3/render_signal_analyzer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/residual_echo_estimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/reverb_decay_estimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/reverb_frequency_response.cc
	${webrtc_source_path}/modules/audio_processing/aec3/reverb_model.cc
	${webrtc_source_path}/modules/audio_processing/aec3/reverb_model_estimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/shadow_filter_update_gain.cc
	${webrtc_source_path}/modules/audio_processing/aec3/signal_dependent_erle_estimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/spectrum_buffer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/stationarity_estimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/subband_erle_estimator.cc
	${webrtc_source_path}/modules/audio_processing/aec3/subtractor.cc
	${webrtc_source_path}/modules/audio_processing/aec3/subtractor_output.cc
	${webrtc_source_path}/modules/audio_processing/aec3/subtractor_output_analyzer.cc
	${webrtc_source_path}/modules/audio_processing/aec3/suppression_filter.cc
	${webrtc_source_path}/modules/audio_processing/aec3/suppression_gain.cc
	${webrtc_source_path}/modules/audio_processing/aec_dump/null_aec_dump_factory.cc
	${webrtc_source_path}/modules/audio_processing/aecm/aecm_core.cc
	${webrtc_source_path}/modules/audio_processing/aecm/aecm_core_c.cc
	${webrtc_source_path}/modules/audio_processing/aecm/echo_control_mobile.cc
	${webrtc_source_path}/modules/audio_processing/agc/agc.cc
	${webrtc_source_path}/modules/audio_processing/agc/agc_manager_direct.cc
	${webrtc_source_path}/modules/audio_processing/agc/utility.cc
	${webrtc_source_path}/modules/audio_processing/agc/legacy/analog_agc.c
	${webrtc_source_path}/modules/audio_processing/agc/legacy/digital_agc.c
	${webrtc_source_path}/modules/audio_processing/agc/loudness_histogram.cc
	${webrtc_source_path}/modules/audio_processing/agc2/agc2_common.cc
	${webrtc_source_path}/modules/audio_processing/agc2/adaptive_agc.cc
	${webrtc_source_path}/modules/audio_processing/agc2/adaptive_digital_gain_applier.cc
	${webrtc_source_path}/modules/audio_processing/agc2/adaptive_mode_level_estimator.cc
	${webrtc_source_path}/modules/audio_processing/agc2/adaptive_mode_level_estimator_agc.cc
	${webrtc_source_path}/modules/audio_processing/agc2/biquad_filter.cc
	${webrtc_source_path}/modules/audio_processing/agc2/compute_interpolated_gain_curve.cc
	${webrtc_source_path}/modules/audio_processing/agc2/down_sampler.cc
	${webrtc_source_path}/modules/audio_processing/agc2/fixed_digital_level_estimator.cc
	${webrtc_source_path}/modules/audio_processing/agc2/gain_applier.cc
	${webrtc_source_path}/modules/audio_processing/agc2/interpolated_gain_curve.cc
	${webrtc_source_path}/modules/audio_processing/agc2/limiter.cc
	${webrtc_source_path}/modules/audio_processing/agc2/noise_level_estimator.cc
	${webrtc_source_path}/modules/audio_processing/agc2/noise_spectrum_estimator.cc
	${webrtc_source_path}/modules/audio_processing/agc2/rnn_vad/auto_correlation.cc
	${webrtc_source_path}/modules/audio_processing/agc2/rnn_vad/features_extraction.cc
	${webrtc_source_path}/modules/audio_processing/agc2/rnn_vad/lp_residual.cc
	${webrtc_source_path}/modules/audio_processing/agc2/rnn_vad/pitch_search.cc
	${webrtc_source_path}/modules/audio_processing/agc2/rnn_vad/pitch_search_internal.cc
	${webrtc_source_path}/modules/audio_processing/agc2/rnn_vad/rnn.cc
	${webrtc_source_path}/modules/audio_processing/agc2/rnn_vad/spectral_features.cc
	${webrtc_source_path}/modules/audio_processing/agc2/rnn_vad/spectral_features_internal.cc
	${webrtc_source_path}/modules/audio_processing/agc2/saturation_protector.cc
	${webrtc_source_path}/modules/audio_processing/agc2/signal_classifier.cc
	${webrtc_source_path}/modules/audio_processing/agc2/vad_with_level.cc
	${webrtc_source_path}/modules/audio_processing/agc2/vector_float_frame.cc
	${webrtc_source_path}/modules/audio_processing/agc/agc.cc
	${webrtc_source_path}/modules/audio_processing/agc/agc_manager_direct.cc
	${webrtc_source_path}/modules/audio_processing/agc/loudness_histogram.cc
	${webrtc_source_path}/modules/audio_processing/agc/utility.cc
	${webrtc_source_path}/modules/audio_processing/audio_buffer.cc
	${webrtc_source_path}/modules/audio_processing/audio_processing_impl.cc
	${webrtc_source_path}/modules/audio_processing/echo_control_mobile_impl.cc
	${webrtc_source_path}/modules/audio_processing/echo_detector/circular_buffer.cc
	${webrtc_source_path}/modules/audio_processing/echo_detector/mean_variance_estimator.cc
	${webrtc_source_path}/modules/audio_processing/echo_detector/moving_max.cc
	${webrtc_source_path}/modules/audio_processing/echo_detector/normalized_covariance_estimator.cc
	${webrtc_source_path}/modules/audio_processing/gain_control_impl.cc
	${webrtc_source_path}/modules/audio_processing/gain_controller2.cc
	${webrtc_source_path}/modules/audio_processing/high_pass_filter.cc
	${webrtc_source_path}/modules/audio_processing/include/aec_dump.cc
	${webrtc_source_path}/modules/audio_processing/include/audio_processing.cc
	${webrtc_source_path}/modules/audio_processing/include/audio_processing_statistics.cc
	${webrtc_source_path}/modules/audio_processing/include/config.cc
	${webrtc_source_path}/modules/audio_processing/logging/apm_data_dumper.cc
	${webrtc_source_path}/modules/audio_processing/residual_echo_detector.cc
	${webrtc_source_path}/modules/audio_processing/rms_level.cc
	${webrtc_source_path}/modules/audio_processing/splitting_filter.cc
	${webrtc_source_path}/modules/audio_processing/test/conversational_speech/config.cc
	${webrtc_source_path}/modules/audio_processing/test/conversational_speech/timing.cc
	${webrtc_source_path}/modules/audio_processing/test/py_quality_assessment/quality_assessment/vad.cc
	${webrtc_source_path}/modules/audio_processing/three_band_filter_bank.cc
	${webrtc_source_path}/modules/audio_processing/transient/file_utils.cc
	${webrtc_source_path}/modules/audio_processing/transient/moving_moments.cc
	${webrtc_source_path}/modules/audio_processing/transient/transient_detector.cc
	${webrtc_source_path}/modules/audio_processing/transient/transient_suppressor.cc
	${webrtc_source_path}/modules/audio_processing/transient/wpd_node.cc
	${webrtc_source_path}/modules/audio_processing/transient/wpd_tree.cc
	${webrtc_source_path}/modules/audio_processing/typing_detection.cc
	${webrtc_source_path}/modules/audio_processing/utility/cascaded_biquad_filter.cc
	${webrtc_source_path}/modules/audio_processing/utility/delay_estimator.cc
	${webrtc_source_path}/modules/audio_processing/utility/delay_estimator_wrapper.cc
	${webrtc_source_path}/modules/audio_processing/utility/ooura_fft.cc
	${webrtc_source_path}/modules/audio_processing/utility/pffft_wrapper.cc
	${webrtc_source_path}/modules/audio_processing/vad/gmm.cc
	${webrtc_source_path}/modules/audio_processing/vad/pitch_based_vad.cc
	${webrtc_source_path}/modules/audio_processing/vad/pitch_internal.cc
	${webrtc_source_path}/modules/audio_processing/vad/pole_zero_filter.cc
	${webrtc_source_path}/modules/audio_processing/vad/standalone_vad.cc
	${webrtc_source_path}/modules/audio_processing/vad/vad_audio_proc.cc
	${webrtc_source_path}/modules/audio_processing/vad/vad_circular_buffer.cc
	${webrtc_source_path}/modules/audio_processing/vad/voice_activity_detector.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/alr_detector.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/bitrate_estimator.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/congestion_window_pushback_controller.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/delay_based_bwe.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/goog_cc_network_control.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/link_capacity_estimator.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/median_slope_estimator.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/probe_bitrate_estimator.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/probe_controller.cc
	${webrtc_source_path}/modules/congestion_controller/goog_cc/trendline_estimator.cc
	${webrtc_source_path}/modules/congestion_controller/pcc/bitrate_controller.cc
	${webrtc_source_path}/modules/congestion_controller/receive_side_congestion_controller.cc
	${webrtc_source_path}/modules/congestion_controller/rtp/control_handler.cc
	${webrtc_source_path}/modules/congestion_controller/rtp/transport_feedback_adapter.cc
	${webrtc_source_path}/modules/include/module_common_types.cc
	${webrtc_source_path}/modules/pacing/bitrate_prober.cc
	${webrtc_source_path}/modules/pacing/interval_budget.cc
	${webrtc_source_path}/modules/pacing/paced_sender.cc
	${webrtc_source_path}/modules/pacing/pacing_controller.cc
	${webrtc_source_path}/modules/pacing/packet_router.cc
	${webrtc_source_path}/modules/pacing/round_robin_packet_queue.cc
	${webrtc_source_path}/modules/remote_bitrate_estimator/aimd_rate_control.cc
	${webrtc_source_path}/modules/remote_bitrate_estimator/bwe_defines.cc
	${webrtc_source_path}/modules/remote_bitrate_estimator/inter_arrival.cc
	${webrtc_source_path}/modules/remote_bitrate_estimator/overuse_detector.cc
	${webrtc_source_path}/modules/remote_bitrate_estimator/overuse_estimator.cc
	${webrtc_source_path}/modules/remote_bitrate_estimator/remote_bitrate_estimator_abs_send_time.cc
	${webrtc_source_path}/modules/remote_bitrate_estimator/remote_bitrate_estimator_single_stream.cc
	${webrtc_source_path}/modules/remote_bitrate_estimator/remote_estimator_proxy.cc
	${webrtc_source_path}/modules/rtp_rtcp/include/report_block_data.cc
	${webrtc_source_path}/modules/rtp_rtcp/include/rtp_rtcp_defines.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/absolute_capture_time_receiver.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/absolute_capture_time_sender.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/dtmf_queue.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/fec_private_tables_bursty.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/fec_private_tables_random.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/fec_test_helper.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/flexfec_header_reader_writer.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/flexfec_receiver.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/flexfec_sender.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/forward_error_correction.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/forward_error_correction_internal.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/packet_loss_stats.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/receive_statistics_impl.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/remote_ntp_time_estimator.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_nack_stats.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/app.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/bye.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/common_header.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/compound_packet.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/dlrr.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/extended_jitter_report.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/extended_reports.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/fir.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/loss_notification.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/nack.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/pli.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/psfb.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/rapid_resync_request.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/receiver_report.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/remb.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/remote_estimate.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/report_block.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/rrtr.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/rtpfb.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/sdes.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/sender_report.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/target_bitrate.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/tmmb_item.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/tmmbn.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/tmmbr.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_packet/transport_feedback.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_receiver.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_sender.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_transceiver.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_transceiver_config.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtcp_transceiver_impl.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_dependency_descriptor_extension.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_format.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_format_h264.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_format_video_generic.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_format_vp8.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_format_vp9.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_generic_frame_descriptor.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_generic_frame_descriptor_extension.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_header_extension_map.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_header_extensions.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_header_extension_size.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_packet.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_packet_history.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_packet_received.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_packet_to_send.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_rtcp_impl.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_sender_audio.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_sender.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_sender_video.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_sequence_number_map.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_utility.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/rtp_video_header.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/source_tracker.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/time_util.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/tmmbr_help.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/ulpfec_generator.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/ulpfec_header_reader_writer.cc
	${webrtc_source_path}/modules/rtp_rtcp/source/ulpfec_receiver_impl.cc
	${webrtc_source_path}/modules/third_party/g722/g722_decode.c
	${webrtc_source_path}/modules/third_party/g722/g722_encode.c
	${webrtc_source_path}/modules/utility/source/process_thread_impl.cc
	${webrtc_source_path}/modules/video_coding/decoder_database.cc
	${webrtc_source_path}/modules/video_coding/decoding_state.cc
	${webrtc_source_path}/modules/video_coding/encoded_frame.cc
	${webrtc_source_path}/modules/video_coding/fec_controller_default.cc
	${webrtc_source_path}/modules/video_coding/frame_buffer2.cc
	${webrtc_source_path}/modules/video_coding/frame_buffer.cc
	${webrtc_source_path}/modules/video_coding/frame_object.cc
	${webrtc_source_path}/modules/video_coding/generic_decoder.cc
	${webrtc_source_path}/modules/video_coding/h264_sprop_parameter_sets.cc
	${webrtc_source_path}/modules/video_coding/h264_sps_pps_tracker.cc
	${webrtc_source_path}/modules/video_coding/histogram.cc
	${webrtc_source_path}/modules/video_coding/include/video_codec_interface.cc
	${webrtc_source_path}/modules/video_coding/inter_frame_delay.cc
	${webrtc_source_path}/modules/video_coding/jitter_buffer.cc
	${webrtc_source_path}/modules/video_coding/jitter_estimator.cc
	${webrtc_source_path}/modules/video_coding/loss_notification_controller.cc
	${webrtc_source_path}/modules/video_coding/media_opt_util.cc
	${webrtc_source_path}/modules/video_coding/nack_module.cc
	${webrtc_source_path}/modules/video_coding/packet_buffer.cc
	${webrtc_source_path}/modules/video_coding/packet.cc
	${webrtc_source_path}/modules/video_coding/receiver.cc
	${webrtc_source_path}/modules/video_coding/rtp_frame_reference_finder.cc
	${webrtc_source_path}/modules/video_coding/rtt_filter.cc
	${webrtc_source_path}/modules/video_coding/session_info.cc
	${webrtc_source_path}/modules/video_coding/timestamp_map.cc
	${webrtc_source_path}/modules/video_coding/timing.cc
	${webrtc_source_path}/modules/video_coding/utility/decoded_frames_history.cc
	${webrtc_source_path}/modules/video_coding/utility/frame_dropper.cc
	${webrtc_source_path}/modules/video_coding/utility/framerate_controller.cc
	${webrtc_source_path}/modules/video_coding/utility/ivf_file_writer.cc
	${webrtc_source_path}/modules/video_coding/utility/quality_scaler.cc
	${webrtc_source_path}/modules/video_coding/utility/simulcast_rate_allocator.cc
	${webrtc_source_path}/modules/video_coding/utility/simulcast_utility.cc
	${webrtc_source_path}/modules/video_coding/utility/vp8_header_parser.cc
	${webrtc_source_path}/modules/video_coding/video_codec_initializer.cc
	${webrtc_source_path}/modules/video_coding/video_coding_defines.cc
	${webrtc_source_path}/modules/video_coding/video_coding_impl.cc
	${webrtc_source_path}/modules/video_coding/video_receiver.cc
	${webrtc_source_path}/p2p/base/async_stun_tcp_socket.cc
	${webrtc_source_path}/p2p/base/basic_async_resolver_factory.cc
	${webrtc_source_path}/p2p/base/basic_packet_socket_factory.cc
	${webrtc_source_path}/p2p/base/connection.cc
	${webrtc_source_path}/p2p/base/connection_info.cc
	${webrtc_source_path}/p2p/base/dtls_transport.cc
	${webrtc_source_path}/p2p/base/dtls_transport_internal.cc
	${webrtc_source_path}/p2p/base/ice_credentials_iterator.cc
	${webrtc_source_path}/p2p/base/ice_transport_internal.cc
	${webrtc_source_path}/p2p/base/mdns_message.cc
	${webrtc_source_path}/p2p/base/p2p_constants.cc
	${webrtc_source_path}/p2p/base/p2p_transport_channel.cc
	${webrtc_source_path}/p2p/base/packet_transport_internal.cc
	${webrtc_source_path}/p2p/base/port.cc
	${webrtc_source_path}/p2p/base/port_allocator.cc
	${webrtc_source_path}/p2p/base/port_interface.cc
	${webrtc_source_path}/p2p/base/pseudo_tcp.cc
	${webrtc_source_path}/p2p/base/regathering_controller.cc
	${webrtc_source_path}/p2p/base/stun_port.cc
	${webrtc_source_path}/p2p/base/stun_request.cc
	${webrtc_source_path}/p2p/base/stun_server.cc
	${webrtc_source_path}/p2p/base/tcp_port.cc
	${webrtc_source_path}/p2p/base/transport_description.cc
	${webrtc_source_path}/p2p/base/transport_description_factory.cc
	${webrtc_source_path}/p2p/base/turn_port.cc
	${webrtc_source_path}/p2p/base/turn_server.cc
	${webrtc_source_path}/p2p/client/basic_port_allocator.cc
	${webrtc_source_path}/p2p/client/turn_port_factory.cc
	${webrtc_source_path}/pc/audio_rtp_receiver.cc
	${webrtc_source_path}/pc/audio_track.cc
	${webrtc_source_path}/pc/channel.cc
	${webrtc_source_path}/pc/channel_manager.cc
	${webrtc_source_path}/pc/composite_rtp_transport.cc
	${webrtc_source_path}/pc/data_channel.cc
	${webrtc_source_path}/pc/datagram_rtp_transport.cc
	${webrtc_source_path}/pc/dtls_transport.cc
	${webrtc_source_path}/pc/dtls_srtp_transport.cc
	${webrtc_source_path}/pc/dtmf_sender.cc
	${webrtc_source_path}/pc/external_hmac.cc
	${webrtc_source_path}/pc/ice_server_parsing.cc
	${webrtc_source_path}/pc/ice_transport.cc
	${webrtc_source_path}/pc/jitter_buffer_delay.cc
	${webrtc_source_path}/pc/jsep_ice_candidate.cc
	${webrtc_source_path}/pc/jsep_session_description.cc
	${webrtc_source_path}/pc/jsep_transport.cc
	${webrtc_source_path}/pc/jsep_transport_controller.cc
	${webrtc_source_path}/pc/local_audio_source.cc
	${webrtc_source_path}/pc/media_protocol_names.cc
	${webrtc_source_path}/pc/media_session.cc
	${webrtc_source_path}/pc/media_stream.cc
	${webrtc_source_path}/pc/media_stream_observer.cc
	${webrtc_source_path}/pc/peer_connection.cc
	${webrtc_source_path}/pc/peer_connection_factory.cc
	${webrtc_source_path}/pc/remote_audio_source.cc
	${webrtc_source_path}/pc/rtcp_mux_filter.cc
	${webrtc_source_path}/pc/rtc_stats_collector.cc
	${webrtc_source_path}/pc/rtc_stats_traversal.cc
	${webrtc_source_path}/pc/rtp_media_utils.cc
	${webrtc_source_path}/pc/rtp_parameters_conversion.cc
	${webrtc_source_path}/pc/rtp_receiver.cc
	${webrtc_source_path}/pc/rtp_sender.cc
	${webrtc_source_path}/pc/rtp_transceiver.cc
	${webrtc_source_path}/pc/rtp_transport.cc
	${webrtc_source_path}/pc/sctp_transport.cc
	${webrtc_source_path}/pc/sctp_utils.cc
	${webrtc_source_path}/pc/sdp_serializer.cc
	${webrtc_source_path}/pc/sdp_utils.cc
	${webrtc_source_path}/pc/session_description.cc
	${webrtc_source_path}/pc/simulcast_description.cc
	${webrtc_source_path}/pc/srtp_filter.cc
	${webrtc_source_path}/pc/srtp_session.cc
	${webrtc_source_path}/pc/srtp_transport.cc
	${webrtc_source_path}/pc/stats_collector.cc
	${webrtc_source_path}/pc/track_media_info_map.cc
	${webrtc_source_path}/pc/transport_stats.cc
	${webrtc_source_path}/pc/video_rtp_receiver.cc
	${webrtc_source_path}/pc/video_track.cc
	${webrtc_source_path}/pc/video_track_source.cc
	${webrtc_source_path}/pc/webrtc_sdp.cc
	${webrtc_source_path}/pc/webrtc_session_description_factory.cc
	${webrtc_source_path}/rtc_base/async_invoker.cc
	${webrtc_source_path}/rtc_base/async_packet_socket.cc
	${webrtc_source_path}/rtc_base/async_resolver_interface.cc
	${webrtc_source_path}/rtc_base/async_socket.cc
	${webrtc_source_path}/rtc_base/async_tcp_socket.cc
	${webrtc_source_path}/rtc_base/async_udp_socket.cc
	${webrtc_source_path}/rtc_base/bit_buffer.cc
	${webrtc_source_path}/rtc_base/buffer_queue.cc
	${webrtc_source_path}/rtc_base/byte_buffer.cc
	${webrtc_source_path}/rtc_base/checks.cc
	${webrtc_source_path}/rtc_base/copy_on_write_buffer.cc
	${webrtc_source_path}/rtc_base/cpu_time.cc
	${webrtc_source_path}/rtc_base/crc32.cc
	${webrtc_source_path}/rtc_base/critical_section.cc
	${webrtc_source_path}/rtc_base/crypt_string.cc
	${webrtc_source_path}/rtc_base/data_rate_limiter.cc
	${webrtc_source_path}/rtc_base/event.cc
	${webrtc_source_path}/rtc_base/event_tracer.cc
	${webrtc_source_path}/rtc_base/experiments/alr_experiment.cc
	${webrtc_source_path}/rtc_base/experiments/balanced_degradation_settings.cc
	${webrtc_source_path}/rtc_base/experiments/cpu_speed_experiment.cc
	${webrtc_source_path}/rtc_base/experiments/experimental_screenshare_settings.cc
	${webrtc_source_path}/rtc_base/experiments/field_trial_list.cc
	${webrtc_source_path}/rtc_base/experiments/field_trial_parser.cc
	${webrtc_source_path}/rtc_base/experiments/field_trial_units.cc
	${webrtc_source_path}/rtc_base/experiments/jitter_upper_bound_experiment.cc
	${webrtc_source_path}/rtc_base/experiments/keyframe_interval_settings.cc
	${webrtc_source_path}/rtc_base/experiments/normalize_simulcast_size_experiment.cc
	${webrtc_source_path}/rtc_base/experiments/quality_scaler_settings.cc
	${webrtc_source_path}/rtc_base/experiments/quality_scaling_experiment.cc
	${webrtc_source_path}/rtc_base/experiments/rate_control_settings.cc
	${webrtc_source_path}/rtc_base/experiments/rtt_mult_experiment.cc
	${webrtc_source_path}/rtc_base/experiments/stable_target_rate_experiment.cc
	${webrtc_source_path}/rtc_base/experiments/struct_parameters_parser.cc
	${webrtc_source_path}/rtc_base/fake_clock.cc
	${webrtc_source_path}/rtc_base/fake_ssl_identity.cc
	${webrtc_source_path}/rtc_base/file_rotating_stream.cc
	${webrtc_source_path}/rtc_base/firewall_socket_server.cc
	${webrtc_source_path}/rtc_base/helpers.cc
	${webrtc_source_path}/rtc_base/http_common.cc
	${webrtc_source_path}/rtc_base/ifaddrs_android.cc
	${webrtc_source_path}/rtc_base/ifaddrs_converter.cc
	${webrtc_source_path}/rtc_base/ip_address.cc
	${webrtc_source_path}/rtc_base/location.cc
	${webrtc_source_path}/rtc_base/log_sinks.cc
	${webrtc_source_path}/rtc_base/logging.cc
	${webrtc_source_path}/rtc_base/memory/aligned_malloc.cc
	${webrtc_source_path}/rtc_base/memory/fifo_buffer.cc
	${webrtc_source_path}/rtc_base/memory_stream.cc
	${webrtc_source_path}/rtc_base/memory_usage.cc
	${webrtc_source_path}/rtc_base/message_digest.cc
	${webrtc_source_path}/rtc_base/message_handler.cc
	${webrtc_source_path}/rtc_base/nat_server.cc
	${webrtc_source_path}/rtc_base/nat_socket_factory.cc
	${webrtc_source_path}/rtc_base/nat_types.cc
	${webrtc_source_path}/rtc_base/net_helper.cc
	${webrtc_source_path}/rtc_base/net_helpers.cc
	${webrtc_source_path}/rtc_base/network.cc
	${webrtc_source_path}/rtc_base/network_monitor.cc
	${webrtc_source_path}/rtc_base/network/sent_packet.cc
	${webrtc_source_path}/rtc_base/null_socket_server.cc
	${webrtc_source_path}/rtc_base/numerics/exp_filter.cc
	${webrtc_source_path}/rtc_base/numerics/histogram_percentile_counter.cc
	${webrtc_source_path}/rtc_base/numerics/moving_average.cc
	${webrtc_source_path}/rtc_base/numerics/sample_counter.cc
	${webrtc_source_path}/rtc_base/numerics/samples_stats_counter.cc
	${webrtc_source_path}/rtc_base/openssl_adapter.cc
	${webrtc_source_path}/rtc_base/openssl_certificate.cc
	${webrtc_source_path}/rtc_base/openssl_digest.cc
	${webrtc_source_path}/rtc_base/openssl_identity.cc
	${webrtc_source_path}/rtc_base/openssl_session_cache.cc
	${webrtc_source_path}/rtc_base/openssl_stream_adapter.cc
	${webrtc_source_path}/rtc_base/openssl_utility.cc
	${webrtc_source_path}/rtc_base/physical_socket_server.cc
	${webrtc_source_path}/rtc_base/platform_thread.cc
	${webrtc_source_path}/rtc_base/platform_thread_types.cc
	${webrtc_source_path}/rtc_base/proxy_info.cc
	${webrtc_source_path}/rtc_base/proxy_server.cc
	${webrtc_source_path}/rtc_base/race_checker.cc
	${webrtc_source_path}/rtc_base/random.cc
	${webrtc_source_path}/rtc_base/rate_limiter.cc
	${webrtc_source_path}/rtc_base/rate_statistics.cc
	${webrtc_source_path}/rtc_base/rate_tracker.cc
	${webrtc_source_path}/rtc_base/rtc_certificate.cc
	${webrtc_source_path}/rtc_base/rtc_certificate_generator.cc
	${webrtc_source_path}/rtc_base/server_socket_adapters.cc
	${webrtc_source_path}/rtc_base/signal_thread.cc
	${webrtc_source_path}/rtc_base/socket.cc
	${webrtc_source_path}/rtc_base/socket_adapters.cc
	${webrtc_source_path}/rtc_base/socket_address.cc
	${webrtc_source_path}/rtc_base/socket_address_pair.cc
	${webrtc_source_path}/rtc_base/socket_stream.cc
	${webrtc_source_path}/rtc_base/ssl_adapter.cc
	${webrtc_source_path}/rtc_base/ssl_certificate.cc
	${webrtc_source_path}/rtc_base/ssl_fingerprint.cc
	${webrtc_source_path}/rtc_base/ssl_identity.cc
	${webrtc_source_path}/rtc_base/ssl_stream_adapter.cc
	${webrtc_source_path}/rtc_base/stream.cc
	${webrtc_source_path}/rtc_base/string_encode.cc
	${webrtc_source_path}/rtc_base/strings/audio_format_to_string.cc
	${webrtc_source_path}/rtc_base/strings/string_builder.cc
	${webrtc_source_path}/rtc_base/string_to_number.cc
	${webrtc_source_path}/rtc_base/string_utils.cc
	${webrtc_source_path}/rtc_base/synchronization/rw_lock_posix.cc
	${webrtc_source_path}/rtc_base/synchronization/rw_lock_wrapper.cc
	${webrtc_source_path}/rtc_base/synchronization/sequence_checker.cc
	${webrtc_source_path}/rtc_base/synchronization/yield_policy.cc
	${webrtc_source_path}/rtc_base/system/file_wrapper.cc
	${webrtc_source_path}/rtc_base/task_queue.cc
	${webrtc_source_path}/rtc_base/task_queue_stdlib.cc
	${webrtc_source_path}/rtc_base/task_utils/repeating_task.cc
	${webrtc_source_path}/rtc_base/third_party/base64/base64.cc
	${webrtc_source_path}/rtc_base/third_party/sigslot/sigslot.cc
	${webrtc_source_path}/rtc_base/thread.cc
	${webrtc_source_path}/rtc_base/time/timestamp_extrapolator.cc
	${webrtc_source_path}/rtc_base/timestamp_aligner.cc
	${webrtc_source_path}/rtc_base/time_utils.cc
	${webrtc_source_path}/rtc_base/unique_id_generator.cc
	${webrtc_source_path}/rtc_base/weak_ptr.cc
	${webrtc_source_path}/rtc_base/zero_memory.cc
	${webrtc_source_path}/rtc_tools/rtp_generator/rtp_generator.cc
	${webrtc_source_path}/stats/rtc_stats.cc
	${webrtc_source_path}/stats/rtcstats_objects.cc
	${webrtc_source_path}/stats/rtc_stats_report.cc
	${webrtc_source_path}/system_wrappers/source/clock.cc
	${webrtc_source_path}/system_wrappers/source/cpu_features.cc
	${webrtc_source_path}/system_wrappers/source/cpu_info.cc
	${webrtc_source_path}/system_wrappers/source/field_trial.cc
	${webrtc_source_path}/system_wrappers/source/metrics.cc
	${webrtc_source_path}/system_wrappers/source/rtp_to_ntp_estimator.cc
	${webrtc_source_path}/system_wrappers/source/sleep.cc
	${webrtc_source_path}/test/encoder_settings.cc
	${webrtc_source_path}/test/field_trial.cc
	${webrtc_source_path}/test/testsupport/file_utils.cc
	${webrtc_source_path}/video/buffered_frame_decryptor.cc
	${webrtc_source_path}/video/call_stats.cc
	${webrtc_source_path}/video/encoder_bitrate_adjuster.cc
	${webrtc_source_path}/video/encoder_overshoot_detector.cc
	${webrtc_source_path}/video/encoder_rtcp_feedback.cc
	${webrtc_source_path}/video/frame_dumping_decoder.cc
	${webrtc_source_path}/video/frame_encode_metadata_writer.cc
	${webrtc_source_path}/video/quality_limitation_reason_tracker.cc
	${webrtc_source_path}/video/quality_threshold.cc
	${webrtc_source_path}/video/receive_statistics_proxy.cc
	${webrtc_source_path}/video/report_block_stats.cc
	${webrtc_source_path}/video/rtp_streams_synchronizer.cc
	${webrtc_source_path}/video/rtp_video_stream_receiver.cc
	${webrtc_source_path}/video/send_delay_stats.cc
	${webrtc_source_path}/video/send_statistics_proxy.cc
	${webrtc_source_path}/video/stats_counter.cc
	${webrtc_source_path}/video/stream_synchronization.cc
	${webrtc_source_path}/video/transport_adapter.cc
	${webrtc_source_path}/video/video_quality_observer.cc
	${webrtc_source_path}/video/video_receive_stream.cc
	${webrtc_source_path}/video/video_send_stream.cc
	${webrtc_source_path}/video/video_send_stream_impl.cc
	${webrtc_source_path}/video/video_stream_decoder.cc
	${webrtc_source_path}/video/video_stream_decoder_impl.cc
	${webrtc_source_path}/video/video_stream_encoder.cc
	$<TARGET_OBJECTS:libsrtp>
)

if (WTF_CPU_X86_64 OR WTF_CPU_X86)
	list(APPEND webrtc_SOURCES
		${webrtc_source_path}/common_audio/fir_filter_sse.cc
		${webrtc_source_path}/common_audio/resampler/sinc_resampler_sse.cc
		${webrtc_source_path}/modules/audio_processing/utility/ooura_fft_sse2.cc
		${webrtc_source_path}/modules/video_processing/util/denoiser_filter_sse2.cc
	)
endif()

add_library(webrtc STATIC ${webrtc_SOURCES})

target_compile_options(webrtc PRIVATE
	"$<$<COMPILE_LANGUAGE:CXX>:-std=gnu++11>"
	"-DWEBRTC_WEBKIT_BUILD=1"
	"-w"
)

target_compile_definitions(webrtc PRIVATE
	OPENSSL_NO_ASM
	DISABLE_H265
	DYNAMIC_ANNOTATIONS_ENABLED=1
	EXPAT_RELATIVE_PATH
	HAVE_LRINT
	HAVE_LRINTF
	HAVE_NETINET_IN_H
	HAVE_SCTP
	HAVE_WEBRTC_VIDEO
	HAVE_WEBRTC_VOICE
	JSON_USE_EXCEPTION=0
	NON_WINDOWS_DEFINE
	OPUS_BUILD
	OPUS_EXPORT=
	SCTP_SIMPLE_ALLOCATOR
	SCTP_USE_OPENSSL_SHA1
	VAR_ARRAYS
	WEBRTC_APM_DEBUG_DUMP=0
	WEBRTC_CODEC_G711
	WEBRTC_CODEC_G722
	WEBRTC_CODEC_ILBC
	WEBRTC_CODEC_ISAC
	WEBRTC_CODEC_OPUS
	WEBRTC_CODEC_RED
	WEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE
	WEBRTC_INTELLIGIBILITY_ENHANCER=0
	WEBRTC_POSIX
	WEBRTC_MAC
	WEBRTC_NS_FLOAT
	WEBRTC_OPUS_SUPPORT_120MS_PTIME=0
	WEBRTC_OPUS_VARIABLE_COMPLEXITY=0
	WEBRTC_USE_BUILTIN_OPUS=1
	WEBRTC_USE_BUILTIN_ISAC_FIX=1
	WEBRTC_USE_BUILTIN_ISAC_FLOAT=0
	WTF_USE_DYNAMIC_ANNOTATIONS=1
	RTC_DISABLE_VP9
	_GNU_SOURCE
	__Userspace__
	__Userspace_os_${CMAKE_HOST_SYSTEM_NAME}
)

if (WTF_CPU_ARM)
	target_compile_definitions(webrtc PRIVATE
		WEBRTC_ARCH_ARM=1
	)
elseif (WTF_CPU_ARM64)
	target_compile_definitions(webrtc PRIVATE
		WEBRTC_ARCH_ARM64=1
	)
endif()

target_include_directories(webrtc PRIVATE
	${CMAKE_CURRENT_SOURCE_DIR}/workaround
	${abseil_source_path}
	${boringssl_source_path}/src/include
	${jsoncpp_source_path}/include
	${jsoncpp_source_path}/src/lib_json
	${libsrtp_source_path}/config
	${libsrtp_source_path}/crypto/include
	${libsrtp_source_path}/include
	${libyuv_source_path}/include
	${rnnoise_source_path}
	${usrsctp_source_path}
	${usrsctp_source_path}/usrsctplib
	${usrsctp_source_path}/usrsctplib
	${usrsctp_source_path}/usrsctplib/netinet
	${webrtc_source_path}
	${webrtc_source_path}/common_audio/resampler/include
	${webrtc_source_path}/common_audio/signal_processing/include
	${webrtc_source_path}/common_audio/vad/include
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/include

	${CMAKE_CURRENT_SOURCE_DIR}
	${CMAKE_CURRENT_SOURCE_DIR}/third_party
	${CMAKE_CURRENT_SOURCE_DIR}/third_party/libsrtp/config
)

target_link_libraries(webrtc
	usrsctp
	opus
	jsoncpp_lib
)
